CREATE DATABASE LEADERBOARD



CREATE TABLE LEADERBOARD.TEAM(
TID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TNAME VARCHAR(50) NOT NULL,
CREATION_DATE DATETIME NULL
);

CREATE TABLE LEADERBOARD.MEMBER(
M_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MNAME VARCHAR(100) NOT NULL,
TID INT ,
DOB DATETIME NULL,
GENDER VARCHAR(1) NULL,
 EMAIL VARCHAR(100) NULL,
CREATION_DATE DATETIME NULL,
FOREIGN key(TID) references TEAM(TID)
);

CREATE TABLE LEADERBOARD.EVENT(
EID INT primary KEY NOT NULL auto_increment,
ENAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(150) NULL,
CREATION_DATE datetime NULL
);

CREATE TABLE LEADERBOARD.INDIVIDUALSCORES(
IID INT primary key not  NULL auto_increment,
M_ID INT,
EID INT ,
SCORE INT,
foreign key(M_ID) references MEMBER(M_ID),
foreign key(EID) references   EVENT(EID)
);

CREATE TABLE LEADERBOARD.teamSCORES(
TMID INT primary key not  NULL auto_increment,
TID INT,
EID INT ,
SCORE INT,
foreign key(TID) references TEAM(TID),
foreign key(EID) references   EVENT(EID)
);
DROP TABLE teamSCORES;

CREATE TABLE LEADERBOARD.TEAMSCORES(
TMID INT primary key not  NULL auto_increment,
TID INT,
EID INT ,
SCORE INT,
foreign key(TID) references TEAM(TID),
foreign key(EID) references   EVENT(EID)
);



INSERT INTO TEAM(TNAME,CREATION_DATE) VALUES ('RED',sysdate());
INSERT INTO TEAM(TNAME,CREATION_DATE) VALUES ('BLUE',sysdate());
INSERT INTO TEAM(TNAME,CREATION_DATE) VALUES ('GREEN',sysdate());
INSERT INTO TEAM(TNAME,CREATION_DATE) VALUES ('YELLOW',sysdate());

SELECT * FROM TEAM;

SELECT TNAME FROM TEAM;

INSERT INTO MEMBER(MNAME,TID,DOB,GENDER,EMAIL,CREATION_DATE) VALUES('ASWIN',3,'1997-02-23','M','ASWIN@GMAIL.COM');
SELECT * FROM MEMBER;

INSERT INTO EVENT()VALUES();
SELECT * FROM EVENT;

INSERT INTO INDIVIDUALSCORES() VALUES();
SELECT * FROM INDIVIDUALSCORES;

INSERT INTO TEAMSCORES() VALUES();
SELECT * FROM TEAMSCORES;