CREATE DATABASE LEADERBOARD;
DROP DATABASE LEADERBOARDTEST;
CREATE DATABASE LEADERBOARD;

CREATE TABLE LEADERBOARD.TEAM(

Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TEAMNAME VARCHAR(20) NOT NULL,
CREATIONDATE DATETIME NULL
);

CREATE TABLE LEADERBOARD.MEMBER(

MEMBER_Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MEMBER_Name VARCHAR(100) NOT NULL,
TEAM_Id INT, 
DoB DATETIME,
GENDER VARCHAR(1),
EMAIL VARCHAR(50),
CREATIONDATE DATETIME,
FOREIGN KEY(TEAM_Id) REFERENCES TEAM(Id)
);


CREATE TABLE LEADERBOARD.EVENTS(

EVENT_Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
EVENT_Name VARCHAR(50) NOT NULL,
EVENT_DESCRIPTION VARCHAR(100),
CREATIONDATE DATETIME

);

CREATE TABLE LEADERBOARD.INDIVIDUALSCORE(

ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MEMB_Id INT,
EVNT_Id INT,
MEMBER_SCORE INT NOT NULL,
CREATIONDATE DATETIME,
FOREIGN KEY(MEMB_Id) REFERENCES MEMBER(MEMBER_Id),
FOREIGN KEY(EVNT_Id) REFERENCES EVENTS(EVENT_Id)

);


CREATE TABLE LEADERBOARD.TEAMSCORE(

Id_No int primary key not null auto_increment,
TEAM_Id int,
EVNT_Id INT,
tm_score int,
FOREIGN KEY(EVNT_Id) REFERENCES EVENTS(EVENT_Id),
FOREIGN KEY(TEAM_Id) REFERENCES TEAM(Id)

);


INSERT INTO LEADERBOARD.TEAM(TEAMNAME,CREATIONDATE) VALUES('RED',sysdate());
INSERT INTO LEADERBOARD.TEAM(TEAMNAME,CREATIONDATE) VALUES('BLUE',sysdate());
INSERT INTO LEADERBOARD.TEAM(TEAMNAME,CREATIONDATE) VALUES('YELLOW',sysdate());
INSERT INTO LEADERBOARD.TEAM(TEAMNAME,CREATIONDATE) VALUES('GREEN',sysdate());

SELECT * FROM LEADERBOARD.TEAM;

INSERT INTO LEADERBOARD.MEMBER(MEMBER_NAME,TEAM_Id,GENDER,EMAIL,CREATIONDATE) VALUES('SRUTHY',1,'F','sruthyp@gmail.com',sysdate());
SELECT * FROM LEADERBOARD.MEMBER;



INSERT INTO LEADERBOARD.MEMBER(MEMBER_NAME,TEAM_Id,DoB,GENDER,EMAIL,CREATIONDATE) VALUES('ANITTA',1,'1995-03-15','F','anitta@gmail.com',sysdate());


INSERT INTO LEADERBOARD.MEMBER(MEMBER_NAME,TEAM_Id,DoB,GENDER,EMAIL,CREATIONDATE) VALUES('DIVYA',2,'1994-04-15','F','divya1@gmail.com',sysdate());
INSERT INTO LEADERBOARD.MEMBER(MEMBER_NAME,TEAM_Id,DoB,GENDER,EMAIL,CREATIONDATE) VALUES('ASWIN',2,'1990-10-1','M','aswin12@gmail.com',sysdate());


